name: Multisite CI/CD Workflow

on:
  push:
    branches:
      - develop
      - main
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Code ophalen uit de repository
      - name: Check out code
        uses: actions/checkout@v3

      # PHP opzetten
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, intl

      # Composer dependencies installeren
      - name: Install Composer Dependencies
        working-directory: ./bryandeknikker-develix
        run: composer install --prefer-dist --no-progress --no-dev

      # Node.js opzetten
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # NPM dependencies installeren
      - name: Install NPM Dependencies
        working-directory: ./bryandeknikker-develix
        run: npm install

      # Assets bouwen
      - name: Build Assets
        working-directory: ./bryandeknikker-develix
        run: npm run build

  deploy:
    needs: build
    if: github.ref == 'refs/heads/production'
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Deploy to Vimexx Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          set -e # Stop bij fouten

          echo "=== Setting up SSH ==="
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 7685 -H 185.104.29.158 >> ~/.ssh/known_hosts

          echo "=== Testing SSH connection ==="
          ssh -i ~/.ssh/id_rsa -p 7685 -o StrictHostKeyChecking=no u181065p251251@185.104.29.158 "echo 'SSH connection successful'"

          # Sync Laravel kernbestanden naar server
          echo "=== Syncing Laravel Core Files ==="
          rsync -avz -e "ssh -i ~/.ssh/id_rsa -p 7685" --exclude "node_modules" --exclude ".git" \
            ./bryandeknikker-develix/ u181065p251251@185.104.29.158:/home/u181065p251251/laravel_app/

          # Stel symlinks in voor de domeinen
          echo "=== Setting Up bryandeknikker.nl ==="
          ssh -i ~/.ssh/id_rsa -p 7685 -o StrictHostKeyChecking=no u181065p251251@185.104.29.158 "
            ln -sf /home/u181065p251251/laravel_app/public /home/u181065p251251/domains/bryandeknikker.nl/public_html
          "

          echo "=== Setting Up develix.nl ==="
          ssh -i ~/.ssh/id_rsa -p 7685 -o StrictHostKeyChecking=no u181065p251251@185.104.29.158 "
            ln -sf /home/u181065p251251/laravel_app/public /home/u181065p251251/domains/develix.nl/public_html
          "

          # Composer install uitvoeren
          echo "=== Running Composer Install ==="
          ssh -i ~/.ssh/id_rsa -p 7685 -o StrictHostKeyChecking=no u181065p251251@185.104.29.158 "
            cd /home/u181065p251251/laravel_app
            composer install --no-dev --optimize-autoloader
          "

          # Machtigingen instellen voor opslag en cache
          echo "=== Setting Permissions ==="
          ssh -i ~/.ssh/id_rsa -p 7685 -o StrictHostKeyChecking=no u181065p251251@185.104.29.158 "
            chmod -R 775 /home/u181065p251251/laravel_app/storage
            chmod -R 775 /home/u181065p251251/laravel_app/bootstrap/cache
          "

          echo "=== Deployment Complete ==="