name: Multisite CI/CD Workflow

on:
  push:
    branches:
      - develop
      - main
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Code ophalen uit de repository
      - name: Check out code
        uses: actions/checkout@v3

      # PHP opzetten
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, intl

      # Composer dependencies installeren
      - name: Install Composer Dependencies
        working-directory: ./bryandeknikker-develix
        run: composer install --prefer-dist --no-progress --no-dev

      # Lint PHP code
      - name: Run PHP Linter (Laravel Pint)
        working-directory: ./bryandeknikker-develix
        run: vendor/bin/pint

      # Node.js opzetten
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # NPM dependencies installeren
      - name: Install NPM Dependencies
        working-directory: ./bryandeknikker-develix
        run: npm install

      # Lint JavaScript code
      - name: Run JavaScript Linter (ESLint)
        working-directory: ./bryandeknikker-develix
        run: npx eslint resources/js/**/*.js

      # Assets bouwen
      - name: Build Assets
        working-directory: ./bryandeknikker-develix
        run: npm run build

  deploy:
    if: github.ref == 'refs/heads/production'
    runs-on: ubuntu-latest

    steps:
      # Code ophalen uit de repository
      - name: Check out code
        uses: actions/checkout@v3

      # PHP opzetten
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      # Composer dependencies installeren
      - name: Install Composer Dependencies
        working-directory: ./bryandeknikker-develix
        run: composer install --prefer-dist --no-progress --no-dev

      # Node.js opzetten
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # NPM dependencies installeren
      - name: Install NPM Dependencies
        working-directory: ./bryandeknikker-develix
        run: npm install

      # Assets bouwen
      - name: Build Assets
        working-directory: ./bryandeknikker-develix
        run: npm run build

      # Deployen naar de Vimexx-server
      - name: Deploy to Vimexx Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VIMEXX_WEBSITE }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          BASE_DEPLOY_PATH: ${{ secrets.BASE_DEPLOY_PATH }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

          # Synchroniseer de volledige codebase naar het basispad
          rsync -avz --delete ./bryandeknikker-develix/ $SERVER_IP:$BASE_DEPLOY_PATH

          # Synchroniseer naar specifieke domeinen
          ssh $SERVER_IP "cd $BASE_DEPLOY_PATH && rsync -avz --delete ./ bryandeknikker.nl/"
          ssh $SERVER_IP "cd $BASE_DEPLOY_PATH && rsync -avz --delete ./ develix.nl/"